// <auto-generated />
using BankServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankLibrary.Transaction", b =>
                {
                    b.Property<int>("TransactionReference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EndBalance")
                        .HasColumnType("float");

                    b.Property<double>("Mutation")
                        .HasColumnType("float");

                    b.Property<double>("StartBalance")
                        .HasColumnType("float");

                    b.HasKey("TransactionReference");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionReference = 1,
                            AccountNumber = "NL10RABO9182987610",
                            Description = "Food",
                            EndBalance = 965.0,
                            Mutation = -35.950000000000003,
                            StartBalance = 1000.95
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
